### ISSUE TITLE
create edit profile form

### ISSUE THREAD

**Issue by sabinaander** [A-Ozmehak/Go-Rent#78]
As a user it would be nice to edit my profile page. 

I would like to be able to edit these fields:
- profile picture
- my bio
- my location
- my username

**Comment by sabinaander** [comment]
Criterias:
- if a user is visiting their own profile and is signed in ( isLoggedInUser && isCurrentUser ) show a edit icon on their profile on hover
- when clicking said icon, open up a form with:
- a title : "Redigera din profil"
         - edit fields:
            - profile picture
            -  username
            - bio
            - location
            - delete account button
            - submit button

**Comment by A-Ozmehak** [comment]
- [ ] if a user is visiting their own profile and is signed in ( isLoggedInUser && isCurrentUser(query params on the profile) ) show a edit icon on their profile on hover
- [ ] when clicking said icon, open up a form with:
- [ ] a title : "Redigera din profil"
- edit fields:
- profile picture
- username
- bio
- location
- delete account button
- submit button
